spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    hikari:
      connection-test-query: SELECT 1
      
jpa: 
  database: h2
  show-sql: true
  generate-ddl: true
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  